<?php

return [
    'MIDTRANS_MERCHAT_ID' => env('MIDTRANS_MERCHAT_ID'),
    'MIDTRANS_CLIENT_KEY' => env('MIDTRANS_CLIENT_KEY'),
    'MIDTRANS_SERVER_KEY' => env('MIDTRANS_SERVER_KEY'),

    'MIDTRANS_IS_PRODUCTION' => env('MIDTRANS_IS_PRODUCTION'),
    'MIDTRANS_IS_SANITIZED' => env('MIDTRANS_IS_SANITIZED'),
    'MIDTRANS_IS_3DS' => env('MIDTRANS_IS_3DS'),
];
