import Head from "next/head";
import Header from "../Header";
import React from "react";

interface Props {
  children: React.ReactNode;
}

export default function Landing({ children }: Props) {
  return (
    <>
      <Head>
        <title>
          Million Candles | Produsen Lilin, Souvenir Lilin Skala UMKM Yogyakarta
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
    </>
  );
}
