import Head from "next/head";
import Header from "../Header";
import React from "react";
import Footer from "components/Footer";

interface Props {
  children: React.ReactNode;
}

export default function Landing({ children }: Props) {
  return (
    <>
      <Head>
        <title>
          Produsen Supplier Lilin, Lilin Aromaterapi, Lilin Ibadah, Lilin Pilar,
          Lilin Sembhayang, Lilin Gelas, Lilin Acara, Lilin Mati Lampu, Pabrik
          Lilin, Souvenir Lilin, Yogyakarta | Million Candles
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
      <Footer />
    </>
  );
}
