// Province name mapping
export const provinceNames = {
  IDAC: "Aceh",
  IDBA: "Bali",
  IDBB: "Bangka-Belitung",
  IDBE: "Bengkulu",
  IDBT: "Banten",
  IDGO: "Gorontalo",
  IDJA: "Jambi",
  IDJB: "Jawa Barat",
  IDJI: "Jawa Timur",
  IDJK: "Jakarta Raya",
  IDJT: "Jawa Tengah",
  IDKB: "Kalimantan Barat",
  IDKI: "Kalimantan Timur",
  IDKR: "Kepulauan Riau",
  IDKS: "Kalimantan Selatan",
  IDKT: "Kalimantan Tengah",
  IDKU: "North Kalimantan",
  IDLA: "Lampung",
  IDMA: "Maluku",
  IDMU: "Maluku Utara",
  IDNB: "Nusa Tenggara Barat",
  IDNT: "Nusa Tenggara Timur",
  IDPA: "Papua",
  IDPB: "Papua Barat",
  IDRI: "Riau",
  IDSA: "Sulawesi Utara",
  IDSB: "Sumatera Barat",
  IDSG: "Sulawesi Tenggara",
  IDSN: "Sulawesi Selatan",
  IDSR: "Sulawesi Barat",
  IDSS: "Sumatera Selatan",
  IDST: "Sulawesi Tengah",
  IDSU: "Sumatera Utara",
  IDYO: "Yogyakarta",
};

// Sample data with detailed information - replace with your actual data
export const sampleData = {
  IDAC: { value: 75, customers: 12, growth: "+5%" },
  IDBA: { value: 90, customers: 18, growth: "+7%" },
  IDBB: { value: 45, customers: 9, growth: "+2%" },
  IDBE: { value: 60, customers: 6, growth: "+1%" },
  IDBT: { value: 85, customers: 17, growth: "+6%" },
  IDGO: { value: 30, customers: 4, growth: "0%" },
  IDJA: { value: 50, customers: 10, growth: "+3%" },
  IDJB: { value: 95, customers: 25, growth: "+10%" },
  IDJI: { value: 80, customers: 20, growth: "+6%" },
  IDJK: { value: 100, customers: 30, growth: "+15%" },
  IDJT: { value: 70, customers: 14, growth: "+4%" },
  IDKB: { value: 40, customers: 5, growth: "+1%" },
  IDKI: { value: 65, customers: 8, growth: "+2%" },
  IDKR: { value: 55, customers: 7, growth: "+3%" },
  IDKS: { value: 75, customers: 10, growth: "+5%" },
  IDKT: { value: 35, customers: 4, growth: "0%" },
  IDKU: { value: 25, customers: 3, growth: "-1%" },
  IDLA: { value: 60, customers: 9, growth: "+4%" },
  IDMA: { value: 45, customers: 6, growth: "+2%" },
  IDMU: { value: 30, customers: 3, growth: "0%" },
  IDNB: { value: 70, customers: 10, growth: "+5%" },
  IDNT: { value: 50, customers: 7, growth: "+3%" },
  IDPA: { value: 20, customers: 2, growth: "-2%" },
  IDPB: { value: 15, customers: 1, growth: "-3%" },
  IDRI: { value: 65, customers: 11, growth: "+4%" },
  IDSA: { value: 40, customers: 5, growth: "+1%" },
  IDSB: { value: 80, customers: 16, growth: "+8%" },
  IDSG: { value: 35, customers: 4, growth: "+1%" },
  IDSN: { value: 75, customers: 15, growth: "+6%" },
  IDSR: { value: 25, customers: 3, growth: "-1%" },
  IDSS: { value: 60, customers: 8, growth: "+3%" },
  IDST: { value: 50, customers: 6, growth: "+2%" },
  IDSU: { value: 85, customers: 21, growth: "+9%" },
  IDYO: { value: 90, customers: 22, growth: "+8%" },
};
