name: Generate Daily Article

permissions:
  contents: write

on:
  # Menjalankan setiap hari jam 00:00 UTC (jam 7 pagi WIB)
  schedule:
    - cron: "0 0,8,16 * * *"

  # Tombol manual untuk menjalankan workflow dari tab Actions di GitHub
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout kode dari repositori
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9 # Anda bisa sesuaikan dengan versi pnpm yang Anda gunakan

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Gunakan versi LTS Node.js
          cache: "pnpm"

      # 3. Install dependencies
      - name: Install dependencies
        run: pnpm install

      # 4. Jalankan skrip pembuat artikel
      - name: Generate New Article
        run: pnpm run new-article
        env:
          # Ambil API Key dari Secrets GitHub
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Build the Site
        run: pnpm run build

      - name: Check file status before commit
        run: git status

      # 5. Commit file baru ke repo
      - name: Commit new article
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat(blog): ✨ Add new tutorial article"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"
          file_pattern: .
